// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiVUn1JXB4bIk58otqn7DvDWJXiTGM0YQ',
    appId: '1:749983421630:web:1a2bc105941719b813baef',
    messagingSenderId: '749983421630',
    projectId: 'inclujob-446a1',
    authDomain: 'inclujob-446a1.firebaseapp.com',
    storageBucket: 'inclujob-446a1.firebasestorage.app',
    measurementId: 'G-0VYQC92H6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq6FBK3rJZUFTPU-MaA0zJaRblSmnmM_Y',
    appId: '1:749983421630:android:342e96d6d1ff295713baef',
    messagingSenderId: '749983421630',
    projectId: 'inclujob-446a1',
    storageBucket: 'inclujob-446a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmk7TnGzMg9lULz2tspNrdYvQwNqT6BBI',
    appId: '1:749983421630:ios:99280aae3316ce2613baef',
    messagingSenderId: '749983421630',
    projectId: 'inclujob-446a1',
    storageBucket: 'inclujob-446a1.firebasestorage.app',
    iosClientId: '749983421630-2h3v4k94u1s1cv39n2ct6unpls256cco.apps.googleusercontent.com',
    iosBundleId: 'com.example.inclujob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmk7TnGzMg9lULz2tspNrdYvQwNqT6BBI',
    appId: '1:749983421630:ios:99280aae3316ce2613baef',
    messagingSenderId: '749983421630',
    projectId: 'inclujob-446a1',
    storageBucket: 'inclujob-446a1.firebasestorage.app',
    iosClientId: '749983421630-2h3v4k94u1s1cv39n2ct6unpls256cco.apps.googleusercontent.com',
    iosBundleId: 'com.example.inclujob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiVUn1JXB4bIk58otqn7DvDWJXiTGM0YQ',
    appId: '1:749983421630:web:0161066beead16ac13baef',
    messagingSenderId: '749983421630',
    projectId: 'inclujob-446a1',
    authDomain: 'inclujob-446a1.firebaseapp.com',
    storageBucket: 'inclujob-446a1.firebasestorage.app',
    measurementId: 'G-3YEN5Z5ZNK',
  );

}